version: "3.3"
services:
  postgres:
    image: postgres:14-alpine
    env_file:
      - app.env
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    restart: on-failure
    entrypoint:
      [
        "/app/wait-for.sh",
        "postgres:5432",
        "--",
        "/app/main"
      ]
