// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"database/sql"

	"github.com/google/uuid"
)

type Option struct {
	ID          uuid.UUID `db:"id"`
	Pollid      uuid.UUID `db:"pollid"`
	Optionkey   string    `db:"optionkey"`
	Optionvalue string    `db:"optionvalue"`
}

type Poll struct {
	ID             uuid.UUID    `db:"id"`
	Presentationid uuid.UUID    `db:"presentationid"`
	Question       string       `db:"question"`
	Pollindex      int32        `db:"pollindex"`
	Createdat      sql.NullTime `db:"createdat"`
}

type Presentation struct {
	ID               uuid.UUID     `db:"id"`
	Currentpollindex sql.NullInt32 `db:"currentpollindex"`
}

type Vote struct {
	ID        uuid.UUID `db:"id"`
	Pollid    uuid.UUID `db:"pollid"`
	Optionkey string    `db:"optionkey"`
	Clientid  string    `db:"clientid"`
}
